#!/bin/bash -x

set -e

SCRIPT="$(realpath -s "${0}")"
SCRIPT_PATH="$(dirname "${SCRIPT}")"

image=$1

srcdir="$(mktemp -d)"
./elemental unpack-image --image=${image} --target=${srcdir} --local

qemu-img create -f raw disk.img 10G
loopdev=$(losetup -f --show disk.img)
sgdisk -og "${loopdev}"
sgdisk -n 1:2048:4194303 -c 1:"EFI System Partition" -t 1:ef00 "${loopdev}"
sgdisk -n 2:4194304:+0 -c 2:"Root System Partition" -t 2:8300 "${loopdev}"
partx -u "${loopdev}"
mkfs.vfat -F 16 -n EFI "${loopdev}p1"
mkfs.ext4 -L SYSTEM "${loopdev}p2"
partx -u "${loopdev}"

# Install EFI
efidir=/mnt/efi

mkdir -p "${efidir}"
mount "${loopdev}p1" "${efidir}"

cp -r "${srcdir}"/boot/* ${efidir}/

umount "${efidir}"

# Install dummy rootfs
workdir=/mnt/work

mkdir -p "${workdir}"
mount "${loopdev}p2" "${workdir}"

cp -r "${srcdir}"/* ${workdir}/

umount "${workdir}"

losetup -D "${loopdev}"

rm -rf "${srcdir}"
